"
Boostraph glyph icon
"
Class {
	#name : #TBSGlyphTag,
	#superclass : #WATagBrush,
	#category : 'Bootstrap-Core-Canvas'
}

{ #category : #'default icons' }
TBSGlyphTag >> iconAdjust [

	^self class: 'glyphicon-adjust'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconAlignCenter [

	^self class: 'glyphicon-align-center'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconAlignJustify [

	^self class: 'glyphicon-align-justify'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconAlignLeft [

	^self class: 'glyphicon-align-left'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconAlignRight [

	^self class: 'glyphicon-align-right'
]

{ #category : #'default icons arrows' }
TBSGlyphTag >> iconArrowDown [

	^self class: 'glyphicon-arrow-down'
]

{ #category : #'default icons arrows' }
TBSGlyphTag >> iconArrowLeft [

	^self class: 'glyphicon-arrow-left'
]

{ #category : #'default icons arrows' }
TBSGlyphTag >> iconArrowRight [

	^self class: 'glyphicon-arrow-right'
]

{ #category : #'default icons arrows' }
TBSGlyphTag >> iconArrowUp [

	^self class: 'glyphicon-arrow-up'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconAsterisk [

	^self class: 'glyphicon-asterisk'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconBackward [

	^self class: 'glyphicon-backward'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconBanCircle [

	^self class: 'glyphicon-ban-circle'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconBarcode [

	^self class: 'glyphicon-barcode'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconBell [

	^self class: 'glyphicon-bell'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconBold [

	^self class: 'glyphicon-bold'
]

{ #category : #'default icons internet' }
TBSGlyphTag >> iconBook [

	^self class: 'glyphicon-book'
]

{ #category : #'default icons internet' }
TBSGlyphTag >> iconBookmark [

	^self class: 'glyphicon-bookmark'
]

{ #category : #'default icons money' }
TBSGlyphTag >> iconBriefcase [

	^self class: 'glyphicon-briefcase'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconBullhorn [

	^self class: 'glyphicon-bullhorn'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconCalendar [

	^self class: 'glyphicon-calendar'
]

{ #category : #'default icons media video' }
TBSGlyphTag >> iconCamera [

	^self class: 'glyphicon-camera'
]

{ #category : #'default icons legal' }
TBSGlyphTag >> iconCertificate [

	^self class: 'glyphicon-certificate'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconCheck [

	^self class: 'glyphicon-check'
]

{ #category : #'default icons arrows' }
TBSGlyphTag >> iconChevronDown [

	^self class: 'glyphicon-chevron-down'
]

{ #category : #'default icons arrows' }
TBSGlyphTag >> iconChevronLeft [

	^self class: 'glyphicon-chevron-left'
]

{ #category : #'default icons arrows' }
TBSGlyphTag >> iconChevronRight [

	^self class: 'glyphicon-chevron-right'
]

{ #category : #'default icons arrows' }
TBSGlyphTag >> iconChevronUp [

	^self class: 'glyphicon-chevron-up'
]

{ #category : #'default icons arrows' }
TBSGlyphTag >> iconCircleArrowDown [

	^self class: 'glyphicon-circle-arrow-down'
]

{ #category : #'default icons arrows' }
TBSGlyphTag >> iconCircleArrowLeft [

	^self class: 'glyphicon-circle-arrow-left'
]

{ #category : #'default icons arrows' }
TBSGlyphTag >> iconCircleArrowRight [

	^self class: 'glyphicon-circle-arrow-right'
]

{ #category : #'default icons arrows' }
TBSGlyphTag >> iconCircleArrowUp [

	^self class: 'glyphicon-circle-arrow-up'
]

{ #category : #'default icons internet' }
TBSGlyphTag >> iconCloud [

	^self class: 'glyphicon-cloud'
]

{ #category : #'default icons internet' }
TBSGlyphTag >> iconCloudDownload [

	^self class: 'glyphicon-cloud-download'
]

{ #category : #'default icons internet' }
TBSGlyphTag >> iconCloudUpload [

	^self class: 'glyphicon-cloud-upload'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconCog [

	^self class: 'glyphicon-cog'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconCollapseDown [

	^self class: 'glyphicon-collapse-down'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconCollapseUp [

	^self class: 'glyphicon-collapse-up'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconComment [

	^self class: 'glyphicon-comment'
]

{ #category : #'default icons internet' }
TBSGlyphTag >> iconCompressed [

	^self class: 'glyphicon-compressed'
]

{ #category : #'default icons legal' }
TBSGlyphTag >> iconCopyrightMark [

	^self class: 'glyphicon-copyright-mark'
]

{ #category : #'default icons money' }
TBSGlyphTag >> iconCreditCard [

	^self class: 'glyphicon-credit-card'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconCutlery [

	^self class: 'glyphicon-cutlery'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconDashbord [

	^self class: 'glyphicon-dashboard'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconDownload [

	^self class: 'glyphicon-download'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconDownloadAlt [

	^self class: 'glyphicon-download-alt'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconEarphone [

	^self class: 'glyphicon-earphone'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconEdit [

	^self class: 'glyphicon-edit'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconEject [

	^self class: 'glyphicon-eject'
]

{ #category : #'default icons money' }
TBSGlyphTag >> iconEnvelope [

	^self class: 'glyphicon-envelope'
]

{ #category : #'default icons money' }
TBSGlyphTag >> iconEuro [

	^self class: 'glyphicon-euro'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconExclamationSign [

	^self class: 'glyphicon-exclamation-sign'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconExpand [

	^self class: 'glyphicon-expand'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconExport [

	^self class: 'glyphicon-export'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconEyeClose [

	^self class: 'glyphicon-eye-close'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconEyeOpen [

	^self class: 'glyphicon-eye-open'
]

{ #category : #'default icons media video' }
TBSGlyphTag >> iconFacetimeVideo [

	^self class: 'glyphicon-facetime-video'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconFastBackward [

	^self class: 'glyphicon-fast-backward'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconFastForward [

	^self class: 'glyphicon-fast-forward'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconFile [

	^self class: 'glyphicon-file'
]

{ #category : #'default icons media video' }
TBSGlyphTag >> iconFilm [

	^self class: 'glyphicon-film'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconFilter [

	^self class: 'glyphicon-filter'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconFire [

	^self class: 'glyphicon-fire'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconFlag [

	^self class: 'glyphicon-flag'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconFlash [

	^self class: 'glyphicon-flash'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconFloppyDisk [

	^self class: 'glyphicon-floppy-disk'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconFloppyOpen [

	^self class: 'glyphicon-floppy-open'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconFloppyRemove [

	^self class: 'glyphicon-floppy-remove'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconFloppySave [

	^self class: 'glyphicon-floppy-save'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconFloppySaved [

	^self class: 'glyphicon-floppy-saved'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconFolderClose [

	^self class: 'glyphicon-folder-close'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconFolderOpen [

	^self class: 'glyphicon-folder-open'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconFont [

	^self class: 'glyphicon-font'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconForward [

	^self class: 'glyphicon-forward'
]

{ #category : #'default icons sizing' }
TBSGlyphTag >> iconFullscreen [

	^self class: 'glyphicon-fullscreen'
]

{ #category : #'default icons money' }
TBSGlyphTag >> iconGBP [

	^self class: 'glyphicon-gbp'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconGift [

	^self class: 'glyphicon-gift'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconGlass [

	^self class: 'glyphicon-glass'
]

{ #category : #'default icons internet' }
TBSGlyphTag >> iconGlobe [

	^self class: 'glyphicon-globe'
]

{ #category : #'default icons media video' }
TBSGlyphTag >> iconHDVideo [

	^self class: 'glyphicon-hd-video'
]

{ #category : #'default icons hands' }
TBSGlyphTag >> iconHandDown [

	^self class: 'glyphicon-hand-down'
]

{ #category : #'default icons hands' }
TBSGlyphTag >> iconHandLeft [

	^self class: 'glyphicon-hand-left'
]

{ #category : #'default icons hands' }
TBSGlyphTag >> iconHandRight [

	^self class: 'glyphicon-hand-right'
]

{ #category : #'default icons hands' }
TBSGlyphTag >> iconHandUp [

	^self class: 'glyphicon-hand-up'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconHardDiskDrive [

	^self class: 'glyphicon-hdd'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconHeader [

	^self class: 'glyphicon-header'
]

{ #category : #'default icons media audio' }
TBSGlyphTag >> iconHeadphones [

	^self class: 'glyphicon-headphones'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconHeart [

	^self class: 'glyphicon-heart'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconHeartEmpty [

	^self class: 'glyphicon-heart-empty'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconHome [

	^self class: 'glyphicon-home'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconImport [

	^self class: 'glyphicon-import'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconInbox [

	^self class: 'glyphicon-inbox'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconIndentLeft [

	^self class: 'glyphicon-indent-left'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconIndentRight [

	^self class: 'glyphicon-indent-right'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconInfo [

	^self class: 'glyphicon-info-sign'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconItalic [

	^self class: 'glyphicon-italic'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconLeaf [

	^self class: 'glyphicon-leaf'
]

{ #category : #'default icons internet' }
TBSGlyphTag >> iconLink [

	^self class: 'glyphicon-link'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconList [

	^self class: 'glyphicon-list'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconListAlt [

	^self class: 'glyphicon-list-alt'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconLock [

	^self class: 'glyphicon-lock'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconLogin [

	^self class: 'glyphicon-log-in'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconLogout [

	^self class: 'glyphicon-log-out'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconMagnet [

	^self class: 'glyphicon-magnet'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconMapMarker [

	^self class: 'glyphicon-map-marker'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconMinus [

	^self class: 'glyphicon-minus'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconMinusSign [

	^self class: 'glyphicon-minus-sign'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconMove [

	^self class: 'glyphicon-move'
]

{ #category : #'default icons media audio' }
TBSGlyphTag >> iconMusic [

	^self class: 'glyphicon-music'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconNewWindow [

	^self class: 'glyphicon-new-window'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconOff [

	^self class: 'glyphicon-off'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconOk [

	^self class: 'glyphicon-ok'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconOkCircle [

	^self class: 'glyphicon-ok-circle'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconOkSign [

	^self class: 'glyphicon-ok-sign'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconOpen [

	^self class: 'glyphicon-open'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconPaperclip [

	^self class: 'glyphicon-paperclip'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconPause [

	^self class: 'glyphicon-pause'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconPencil [

	^self class: 'glyphicon-pencil'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconPhone [

	^self class: 'glyphicon-phone'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconPhoneAlt [

	^self class: 'glyphicon-phone-alt'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconPicture [

	^self class: 'glyphicon-picture'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconPlane [

	^self class: 'glyphicon-plane'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconPlay [

	^self class: 'glyphicon-play'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconPlayCircle [

	^self class: 'glyphicon-play-circle'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconPlus [

	^self class: 'glyphicon-plus'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconPlusSign [

	^self class: 'glyphicon-plus-sign'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconPrint [

	^self class: 'glyphicon-print'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconPushpin [

	^self class: 'glyphicon-pushpin'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconQRCode [

	^self class: 'glyphicon-qrcode'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconQuestionSign [

	^self class: 'glyphicon-question-sign'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconRandom [

	^self class: 'glyphicon-random'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconRecord [

	^self class: 'glyphicon-record'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconRefresh [

	^self class: 'glyphicon-refresh'
]

{ #category : #'default icons legal' }
TBSGlyphTag >> iconRegistrationMark [

	^self class: 'glyphicon-registration-mark'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconRemove [

	^self class: 'glyphicon-remove'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconRemoveCircle [

	^self class: 'glyphicon-remove-circle'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconRemoveSign [

	^self class: 'glyphicon-remove-sign'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconRepeat [

	^self class: 'glyphicon-repeat'
]

{ #category : #'default icons sizing' }
TBSGlyphTag >> iconResizeFull [

	^self class: 'glyphicon-resize-full'
]

{ #category : #'default icons sizing' }
TBSGlyphTag >> iconResizeHorizontal [

	^self class: 'glyphicon-resize-horizontal'
]

{ #category : #'default icons sizing' }
TBSGlyphTag >> iconResizeSmall [

	^self class: 'glyphicon-resize-small'
]

{ #category : #'default icons sizing' }
TBSGlyphTag >> iconResizeVertical [

	^self class: 'glyphicon-resize-vertical'
]

{ #category : #'default icons sizing' }
TBSGlyphTag >> iconRetweet [

	^self class: 'glyphicon-retweet'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconRoad [

	^self class: 'glyphicon-road'
]

{ #category : #'default icons media video' }
TBSGlyphTag >> iconSDVideo [

	^self class: 'glyphicon-sd-video'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconSave [

	^self class: 'glyphicon-save'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconSaved [

	^self class: 'glyphicon-saved'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconScreenshot [

	^self class: 'glyphicon-screenshot'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconSearch [

	^self class: 'glyphicon-search'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconSend [

	^self class: 'glyphicon-send'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconShare [

	^self class: 'glyphicon-share'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconShareAlt [

	^self class: 'glyphicon-share-alt'
]

{ #category : #'default icons internet' }
TBSGlyphTag >> iconShoppingCart [

	^self class: 'glyphicon-shopping-cart'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconSignal [

	^self class: 'glyphicon-signal'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconSort [

	^self class: 'glyphicon-sort'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconSortByAlphabet [

	^self class: 'glyphicon-sort-by-alphabet'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconSortByAlphabetAlt [

	^self class: 'glyphicon-sort-by-alphabet-alt'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconSortByAttributes [

	^self class: 'glyphicon-sort-by-attributes'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconSortByAttributesAlt [

	^self class: 'glyphicon-sort-by-attributes-alt'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconSortByOrder [

	^self class: 'glyphicon-sort-by-order'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconSortByOrderAlt [

	^self class: 'glyphicon-sort-by-order-alt'
]

{ #category : #'default icons media audio' }
TBSGlyphTag >> iconSound51 [

	^self class: 'glyphicon-sound-5-1'
]

{ #category : #'default icons media audio' }
TBSGlyphTag >> iconSound61 [

	^self class: 'glyphicon-sound-6-1'
]

{ #category : #'default icons media audio' }
TBSGlyphTag >> iconSound71 [

	^self class: 'glyphicon-sound-7-1'
]

{ #category : #'default icons media audio' }
TBSGlyphTag >> iconSoundDolby [

	^self class: 'glyphicon-sound-dolby'
]

{ #category : #'default icons media audio' }
TBSGlyphTag >> iconSoundStereo [

	^self class: 'glyphicon-sound-stereo'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconStar [

	^self class: 'glyphicon-star'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconStarEmpty [

	^self class: 'glyphicon-star-empty'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconStatistics [

	^self class: 'glyphicon-stats'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconStepBackward [

	^self class: 'glyphicon-step-backward'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconStepForward [

	^self class: 'glyphicon-step-forward'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconStop [

	^self class: 'glyphicon-stop'
]

{ #category : #'default icons media navigation' }
TBSGlyphTag >> iconSubtitles [

	^self class: 'glyphicon-subtitles'
]

{ #category : #'default icons internet' }
TBSGlyphTag >> iconTag [

	^self class: 'glyphicon-tag'
]

{ #category : #'default icons internet' }
TBSGlyphTag >> iconTags [

	^self class: 'glyphicon-tags'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconTasks [

	^self class: 'glyphicon-tasks'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconTextHeight [

	^self class: 'glyphicon-text-height'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconTextHeightDefault [

	^self class: 'glyphicon-th'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconTextHeightLarge [

	^self class: 'glyphicon-th-large'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconTextHeightList [

	^self class: 'glyphicon-th-list'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconTextWidth [

	^self class: 'glyphicon-text-width'
]

{ #category : #'default icons hands' }
TBSGlyphTag >> iconThumbsDown [

	^self class: 'glyphicon-thumbs-down'
]

{ #category : #'default icons hands' }
TBSGlyphTag >> iconThumbsUp [

	^self class: 'glyphicon-thumbs-up'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconTime [

	^self class: 'glyphicon-time'
]

{ #category : #'default icons text' }
TBSGlyphTag >> iconTint [

	^self class: 'glyphicon-tint'
]

{ #category : #'default icons' }
TBSGlyphTag >> iconTower [

	^self class: 'glyphicon-tower'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconTransfer [

	^self class: 'glyphicon-transfer'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconTrash [

	^self class: 'glyphicon-trash'
]

{ #category : #'default icons trees' }
TBSGlyphTag >> iconTreeConifer [

	^self class: 'glyphicon-tree-conifer'
]

{ #category : #'default icons trees' }
TBSGlyphTag >> iconTreeDeciduous [

	^self class: 'glyphicon-tree-deciduous'
]

{ #category : #'default icons money' }
TBSGlyphTag >> iconUSD [

	^self class: 'glyphicon-usd'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconUnchecked [

	^self class: 'glyphicon-unchecked'
]

{ #category : #'default icons file handling' }
TBSGlyphTag >> iconUpload [

	^self class: 'glyphicon-upload'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconUser [

	^self class: 'glyphicon-user'
]

{ #category : #'default icons media audio' }
TBSGlyphTag >> iconVolumeDown [

	^self class: 'glyphicon-volume-down'
]

{ #category : #'default icons media audio' }
TBSGlyphTag >> iconVolumeOff [

	^self class: 'glyphicon-volume-off'
]

{ #category : #'default icons media audio' }
TBSGlyphTag >> iconVolumeUp [

	^self class: 'glyphicon-volume-up'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconWarningSign [

	^self class: 'glyphicon-warning-sign'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconWrench [

	^self class: 'glyphicon-wrench'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconZoomIn [

	^self class: 'glyphicon-zoom-in'
]

{ #category : #'default icons common' }
TBSGlyphTag >> iconZoomOut [

	^self class: 'glyphicon-zoom-out'
]

{ #category : #initialization }
TBSGlyphTag >> initialize [
	super initialize.
	self class: 'glyphicon'
]

{ #category : #accessing }
TBSGlyphTag >> tag [

	^'span'
]
