SystemOrganization addCategory: #'Bootstrap-Examples'!
SystemOrganization addCategory: 'Bootstrap-Examples-Browser'!
SystemOrganization addCategory: 'Bootstrap-Examples-Core'!
SystemOrganization addCategory: 'Bootstrap-Examples-Jasny'!
SystemOrganization addCategory: 'Bootstrap-Examples-Widgets-Canvas'!
SystemOrganization addCategory: 'Bootstrap-Examples-Widgets-Components'!
SystemOrganization addCategory: 'Bootstrap-Examples-Widgets-Table'!
SystemOrganization addCategory: 'Bootstrap-Examples-Widgets-VerticalTabs'!
