rendering
renderButtonsOptionsOn: html

	html 
		heading level: 2; with: 'Options'.
	
	html tbsButton 
			beDefault;
			with: 'Default'.
			
	html space.
	
	html tbsButton 
			bePrimary;
			with: 'Primary'.
	
	html space.
						
	html tbsButton 
			beSuccess;			
			with: 'Success'.	
	
	html space.
						
	html tbsButton 
			beInfo;
			with: 'Info'.	
	
	html space.
				
	html tbsButton 
			beWarning;
			with: 'Warning'.	

	html space.
	
	html tbsButton 
			beDanger;
			with: 'Danger'.						 	 
 
	html space.
		
	html tbsButton 
			beLink;
			with: 'Link'.		
